### PR TITLE
[mdDatePicker] Swipe capabilities; button 'Today'; support for min and max date; [mdTimePicker] Button 'Now'; directive on input[type="time"]

### PR DESCRIPTION
**Pull request by simonered**
Please consider to release a new version with these changes.

### CODE REVIEW

**Comment by simonered** [comment]
Added 'Today' and 'Now' buttons in mdDatePickers and mdTimePicker

**Comment by simonered** [comment]
There was an issue calculating month's view days (in mdDatePicker): now fixed.

**Comment by designnotdrum** [comment]
+ 1, please merge ASAP. @simonered what is the syntax for max/min dates?

**Comment by piyushchauhan2011** [comment]
:+1:

**Comment by simonered** [comment]
The syntax is **md-min-date** and **md-max-date** and expect a js date as input.

**Comment by alenaksu** [comment]
I'm a bit busy in these days.
I'll merge as soon as possible with new features like date filtering

 Hold on :)

**Pull request closed without merging**
