### PR TITLE
feat(mdpDatePicker): allow dynamic placeholder

### PR DESCRIPTION
**Pull request by marcomafessolli**
Allow dynamic placeholder at `mdpPlaceholder` by using `{{}}`

### CODE REVIEW

**Comment by FlorianBurgevin** [comment]
not working for me. Do you have an example?

**Comment by marcomafessolli** [comment]
@FlorianBurgevin Probably it's not working anymore. 

To this feature work properly, at the time we needed to use `angular material release candidate 5`. Check this issue: https://github.com/alenaksu/mdPickers/issues/95.

There's also a mdPickers fork in my profile (`marcomafessolli/mdPickers`) that you could try.

But now I think it's better we close this pull request and create another one with angular material latest version compatibility

**Comment by FlorianBurgevin** [comment]
I just tested with the latest version of angular material (1.1.1)

I tried to add like in your pull request "{{" & "}}" around placeholder. 

But it doesn't seem to display the variable text in the mdPicker. Placeholder is empty like if the library doesn't find the variable (scope inheritance problem?)

**Comment by marcomafessolli** [comment]
@FlorianBurgevin I think you're right. If you want, I can take a look this weekend and create a new pull request (an working one).

For now, I'm gonna close this pull request (not working)

**Comment by FlorianBurgevin** [comment]
@marcomafessolli for the moment I place an empty placeholder. 
But if you have a working pull request I'm interested.

**Comment by marcomafessolli** [comment]
@FlorianBurgevin I'll work on that. Thanks!

**Comment by marcomafessolli** [comment]
@FlorianBurgevin I took a look in the code and actually version 0.7.5 already has this feature (https://github.com/alenaksu/mdPickers/blob/master/src/components/mdpDatePicker/mdpDatePicker.js#L347).

Just use `mdp-placeholder="{{ placeholder }}"`. 

I noticed also that sometimes it doesn't work properly because of `aria-label`, maybe it's related with angular-material version

**Comment by FlorianBurgevin** [comment]
Thank you !

I modified the aria-label with placing an id ahead and it seems to work well !

**Comment by johnrix** [comment]
Not working for me unfortunately. If I inspect the <mdp-date-picker> element, I can see the correctly interpolated value being set by Angular in the mdp-placeholder attribute, but the corresponding <label> element inside the template is not reflecting the updated value. Example (in this instance, `mdp-placeholder="Test {{myExpression}}"`):

    <mdp-date-picker ng-model="attribute.name" mdp-placeholder="Test 232" data-field="EarliestBookingDate" ...
        ...
        <md-input-container md-is-error="isError()" class="md-icon-float">
            <label ng-click="delegateClick()" tabindex="-1" class="ng-binding ng-scope" role="button" for="input_12">Test </label>
        ...

**Pull request closed without merging**
