### PR TITLE
Refactor ( use html templates, ng annotate, and john papa's guidelines )

### PR DESCRIPTION
**Pull request by corentin-gautier**
Hey !

So this is a pretty big refactoring. Feel free to use it or not :) I was trying to reduce the number of scopes in order to boost the perfs but I ended up separating everything in its own file and refactoring the whole thing ^^

There is a very lite performance boost. I will be investigating more in the next few days :)

## Codepen demo
[DEMO](http://codepen.io/corentin-gautier/full/wGxEbe/)

### CODE REVIEW

**Comment by corentin-gautier** [comment]
fixes #83 #54

**Comment by corentin-gautier** [comment]
Add support for disabled ( mdp-disabled )

**Comment by alenaksu** [comment]
@corentin-gautier 
Wow! Thank you for sharing your work. I'll take a look as soon as possible :)

**Comment by corentin-gautier** [comment]
@alenaksu I just pushed a fix for the min and max date: the field was invalid when the user selected the minDate or the maxDate

**Comment by corentin-gautier** [comment]
Also implemented #86 in the refactor

**Comment by flick36** [comment]
Could you add the option to close it when you select the minutes instead of changing the view? :grinning:

**Comment by corentin-gautier** [comment]
@flick36 Done :)

**Comment by flick36** [comment]
you are the man @corentin-gautier !!! thank you!

**Comment by corentin-gautier** [comment]
@flick36 ahah thanks, check out the demo I've just added to the description if you need more infos ;)

**Comment by flick36** [comment]
@corentin-gautier your demo doesn't work :P it won't change to minutes algo i mention earliear in a dialog it closes the parent dialog :P

**Comment by corentin-gautier** [comment]
@flick36 hum this is working fine for me ...

animation

Regarding the dialog closing: you should not use nested dialogs. This is more of an issue related to how the picker works ( I thing there's already an issue asking for a non-dialog based picker )

**Comment by flick36** [comment]
Oh i see, you drag the hours and then it works, but if you click on them it closes, i think it's more natural to click than drag: http://imgur.com/AcxHw9N

**Comment by corentin-gautier** [comment]
@flick36 ok fixed and demo is up to date

**Comment by flick36** [comment]
@corentin-gautier you are friggin awesome, you should create a bower with yours, and mantain it! Thanks!

**Comment by corentin-gautier** [comment]
Fixes #88 ( see demo )

**Comment by flick36** [comment]
it's me again .-., amm when you set the model to the date picker with a valid default date, and the field is required, it will fail the required until you click on the datepicker and select a date, also could you implement the doble click to close or the auto close on click in the datepicker :flushed:

**Comment by corentin-gautier** [comment]
@flick36 this should be fixed now (it works on the demo, can you confirm it works for you ?)

**Comment by flick36** [comment]
The min date it's not working, tri to put 2 date pickers and in one picker put the min date to the model of the other picker, you'll see it works at first, but if you upadate the other model it won't update, also is there a stepper or min and max for the timepicker?

**Comment by AnirudhaGohokar** [comment]
This is awesome.. Thanks @corentin-gautier @alenaksu

**Pull request closed without merging**
