### PR TITLE
(feat)timePicker: add option to switch to the minutes selector after …

### PR DESCRIPTION
**Pull request by corentin-gautier**
… the hour has been picked

(feat)datePicker: add option to customize the date format

- Change toolbar color ( use md-primary )
- Change day color ( use md-primary )

- Remove the check on the input being a date type ( because date type input are ugly for now )

- Improve timePicker toolbar look

- Add live folder with ready to go html for coding purposes ( can also be used for the codepen )

BREAKING CHANGE: $mdpDatePicker & $mdpTimePicker now have a show method in order to show the picker

    change code from : $mdpTimePicker(args).then()

    to

    $mdpTimePicker.show(args).then()

This is quite a lot of changes and you might not agree with everything. I'll just leave this here and if you want you can use it :)

### CODE REVIEW

**Comment by leocaseiro** [comment]
:+1: 

I agree here. After hour pick, it should switch to minutes, as same as the Material Design Specs.

Also agree with input. Sometimes I just want to use an input text with some filter(moment). This probably would fix different format for dates as well. In Australia, we use dd/mm/yyyy instead of mm/dd/yyyy

However, @corentin-gautier. It would be nice, have a pull request for each change. So the owner @alenaksu would choose one by one what he wants.

**Comment by corentin-gautier** [comment]
@leocaseiro will do if he asks me too :)

**Comment by leocaseiro** [comment]
@alenaksu any thoughts?

**Comment by alenaksu** [comment]
@corentin-gautier Thanks for your contribution!

@leocaseiro 
I'm honest, I didn't have time to take a look at the pull request, These days I'm very busy at work.
Please be patient :)

**Comment by corentin-gautier** [comment]
@alenaksu thank you for this plugin ;)

**Comment by leocaseiro** [comment]
@alenaksu I'm really sorry if I push you. Wasn't my intention.

**Pull request closed without merging**
